### ISSUE TITLE
Bank - get bank config

### ISSUE THREAD

**Issue by MathClassIsTough** [thenewboston-developers/thenewboston-python-client#16] opened 2020-11-13 17:16 UTC
# Requirements
- Create a function to get a bank's config
- include any related test(s)

# API Reference
https://thenewboston.com/bank-api/config

**Comment by shahraizali** [comment] 2020-11-13 19:17
Assigned to @jtavak

**Comment by VincentHch** [comment] 2020-11-15 15:46
Sorry for my previous PR, I was working on an old branch

**Comment by VincentHch** [comment] 2020-11-15 16:55
#aaf42054f84c66586bf29d446188347ab910112cb60b775a4d6feadd5b9ae73f

**Comment by CirXe0N** [comment] 2020-11-17 15:14
@shahraizali @VincentHch Can we close this issue? If I am correct we already merged the related PR (https://github.com/thenewboston-developers/thenewboston-python-client/pull/34), right?

**Comment by VincentHch** [comment] 2020-11-17 15:18
The issue can totally be closed

**Comment by VincentHch** [comment] 2020-11-17 15:20
By the way why aren't we paid ? A lot of closed issue are not paid in this repo

**Comment by CirXe0N** [comment] 2020-11-17 15:23
I would think because the issue is not closed yet, but I am not sure. Maybe @shahraizali knows more about how the payment works.

**Comment by shahraizali** [comment] 2020-11-17 15:28
Hi! the issue we usually keep open till it's paid. The payment works such that as soon as the PR is merged we mention the PR or the related issue to the payments channel in slack the payment team then comments down on the Issue that it's paid and then I usually close the issue. let's keep its open but even if its closed the payments team can see the issue because I share the link. they just need to see the amount tag and associate it to your name so that it shows up in the leaderboard.

**Comment by shahraizali** [comment] 2020-11-17 15:30
Sorry for the delays I'll ask for the status.

**Comment by VincentHch** [comment] 2020-11-17 15:48
@shahraizali you assigned the wrong user :)

**Comment by shahraizali** [comment] 2020-11-17 15:53
Sorry, My bad the profile icon got me.

**Comment by odetolataiwo** [comment] 2020-11-17 20:12
@shahraizali  paid

**Closed** 2020-11-18 10:07 UTC
Labels: 5000, Paid
